### ISSUE TITLE
Add tests for basic functionality

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/urchin#16]
Add unit tests for some of the features we implemented:

- Caching needs to be heavily tested
- Database needs to be mocked
- Endpoints need to be tested

**Comment by frankie-mur** [comment]
I need to get better at testing 😆, so I volunteer to take this on!

**Comment by matheusgomes28** [comment]
@frankie-mur I've got a local branch here with some "basic" ping tests for the routes. I looked how how you can mock the database with `Golang` to be able to actually check contents of a webpage, but hadn't finished that work yet.

I'll push it up into a PR tonight and maybe you can pick up from there. There's gonna be some sort of `interface` work with Go so we can mock the Db calls `GetPost`, `GetPosts`, etc.

**Comment by matheusgomes28** [comment]
@frankie-mur , I've added some test examples with Database mocking in #24  . Let me know if you are still interested in working on this, you can take over that PR with your commits if you want.

**Comment by frankie-mur** [comment]
Hey @matheusgomes28, awesome! Yes I can takeover and expand upon
