### ISSUE TITLE
Abstract image file access 

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/urchin#65]
Make the access to the image files happen through an interface. This would make testing the actual business logic of the image endpoints a little easier, so we don't rely on the file system.

For e2e tests, we can still use the filesystem!

This is similar to the `Database` interface we have, but for the images.

**Comment by rafiramadhana** [comment]
Hi @matheusgomes28 , this issue seems interesting to work

However, I have some questions here:
- Does this issue depends on #64? Or we can start to work by abstracting existing files access implementation
- I've read the codebase, it looks like the handlers for image endpoints are located in `./admin-app/image.go`. Which is only `postImageHandler` (as in the `main` branch), is this correct?

**Comment by matheusgomes28** [comment]
Hey @rafiramadhana , thanks for your interest in this task !

Yes, it does depend on that task as the get endpoint for the images need to be merged in for us to abstract it. It should be merged as soon as the suggestions in the PR are fixed 😄

**Comment by rafiramadhana** [comment]
> Yes, it does depend on that task as the get endpoint for the images need to be merged in for us to abstract it. It should be merged as soon as the suggestions in the PR are fixed 😄

Got it. So, let's wait until #64 get merged.

**Comment by matheusgomes28** [comment]
#64 is now merged FYI

**Comment by rafiramadhana** [comment]
@matheusgomes28 Hi, I've just skimmed through the codebase, let's assume we will name our interface as `MediaVault` (as mentioned [here](https://github.com/matheusgomes28/urchin/pull/64#:~:text=something%20like%20a-,MediaVault,-struct%2C%20then%20that))

`MediaVault` will have 3 methods (this is **very open** to discussions and suggestions)

```
type MediaVault interface {
    Add(string) error
    Get(string) ([]byte, error)
    Remove(string) error
}

// Example
err := mv..Add("/file.txt")

b, err := mv.Get("/file.txt")

err := mv.Delete("/file.txt")
```

This `MediaVault` will be implemented in given endpoints:

ADMIN
- GET /images/:id -> not needed. no filesystem op
- POST /images -> `.Add`
- DELETE /images/:id -> `.Delete`

NON-ADMIN
- GET /data/images/:id -> `.Get`

Wdyt?

**Comment by matheusgomes28** [comment]
This has been implemented as a simply static serve to an image directory. 

I also apologise for never rpelying to your message, I probably forgot to 😢
