### ISSUE TITLE
Investigate why we can remove a post twice

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/urchin#77]
Hitting the delete post endpoint (such as `/posts/5`) in the admin app succeeds multiple times. This should not happen as multiple deletions shouldn't work!

**Comment by AlDu2407** [comment]
Hi @matheusgomes28 according to the specification to HTTP the `DELETE` operation is idempotent and therefore should be callable multiple times. Even though the return code can vary. 

![image](https://github.com/matheusgomes28/urchin/assets/40807522/88d4ad30-7789-48de-9a59-0aebb849aa9b)

Ref: https://developer.mozilla.org/en-US/docs/Glossary/Idempotent

**Comment by matheusgomes28** [comment]
Hey @AlDu2407 , that's fine but the issue is that it succeeds more than once - implying that we're not retuning a 404 on the second time

**Comment by matheusgomes28** [comment]
Pretty sure this is no longer a problem
