### ISSUE TITLE
Duplicated `Development` section

### ISSUE THREAD

**Issue by AlDu2407** [matheusgomes28/urchin#84]
In the README.md the process to setup local development is described two times. Those sections should be merged and condensed down to the most important parts.

**Comment by matheusgomes28** [comment]
I'm on this now!

**Comment by matheusgomes28** [comment]
I added the changes [here](https://github.com/matheusgomes28/urchin/pull/85), I'll leave it up for a day or so to give you chance to review it. Thanks for pointing this out Al!

**Comment by AlDu2407** [comment]
Looks good to me now. :) Well done!
